// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.0         [262400]
ROOT Release   : 5.28/00       [334848]
Creator        : tianjp
Date           : Sat Oct 19 22:09:23 2013
Host           : Linux cw103.cc.kek.jp 2.6.18-164.el5 #1 SMP Tue Aug 18 15:51:48 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gpfs/fs01/ilc/tianjp/analysis/PostDBD/zhh/llhh/lepOpt/macros_e1e1hh_bbbb
Training events: 256692
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "True" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10" [Number of updates for regulator before stop training]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
coneec                        coneec                        coneec                        coneec                                                          'c'    [0,458.580871582]
coneen                        coneen                        coneen                        coneen                                                          'c'    [0,228.585403442]
momentum                      momentum                      momentum                      momentum                                                        'm'    [5.00002384186,222.360198975]
coslarcon                     coslarcon                     coslarcon                     coslarcon                                                       'c'    [0.950001418591,1]
energyratio                   energyratio                   energyratio                   energyratio                                                     'e'    [0.0169777330011,1]
ratioecal                     ratioecal                     ratioecal                     ratioecal                                                       'r'    [0.900001347065,1]
ratiototcal                   ratiototcal                   ratiototcal                   ratiototcal                                                     'r'    [0.500000476837,1.29995691776]
nsigd0                        nsigd0                        nsigd0                        nsigd0                                                          'n'    [-13428.9570312,49.9973716736]
nsigz0                        nsigz0                        nsigz0                        nsigz0                                                          'n'    [-6812.04101562,4.9993929863]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "coneec", "coneen", "momentum", "coslarcon", "energyratio", "ratioecal", "ratiototcal", "nsigd0", "nsigz0" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'c';
      fType[1] = 'c';
      fType[2] = 'm';
      fType[3] = 'c';
      fType[4] = 'e';
      fType[5] = 'r';
      fType[6] = 'r';
      fType[7] = 'n';
      fType[8] = 'n';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[15][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.588798379573578;
   fWeightMatrix0to1[1][0] = 0.413014369259017;
   fWeightMatrix0to1[2][0] = -0.561241032975075;
   fWeightMatrix0to1[3][0] = -2.2620081963708;
   fWeightMatrix0to1[4][0] = -1.84037160768317;
   fWeightMatrix0to1[5][0] = -2.22130544678018;
   fWeightMatrix0to1[6][0] = -1.37564568490097;
   fWeightMatrix0to1[7][0] = -0.0313228878971219;
   fWeightMatrix0to1[8][0] = -1.33042790204557;
   fWeightMatrix0to1[9][0] = 0.669342584575784;
   fWeightMatrix0to1[10][0] = -1.91801060895529;
   fWeightMatrix0to1[11][0] = -0.135061410818806;
   fWeightMatrix0to1[12][0] = -2.05943013396923;
   fWeightMatrix0to1[13][0] = 5.01328647757782;
   fWeightMatrix0to1[0][1] = 0.0623925325890237;
   fWeightMatrix0to1[1][1] = -0.911678758384216;
   fWeightMatrix0to1[2][1] = 1.00675897987019;
   fWeightMatrix0to1[3][1] = -0.360361167254816;
   fWeightMatrix0to1[4][1] = 0.249244942053497;
   fWeightMatrix0to1[5][1] = 0.108948049852267;
   fWeightMatrix0to1[6][1] = -1.24210508871457;
   fWeightMatrix0to1[7][1] = 2.67315435829365;
   fWeightMatrix0to1[8][1] = 0.417477651081129;
   fWeightMatrix0to1[9][1] = 0.332057815588127;
   fWeightMatrix0to1[10][1] = -1.26044707390178;
   fWeightMatrix0to1[11][1] = 1.30662932435222;
   fWeightMatrix0to1[12][1] = -0.0848854480191608;
   fWeightMatrix0to1[13][1] = -0.658180353357241;
   fWeightMatrix0to1[0][2] = 1.25296609439396;
   fWeightMatrix0to1[1][2] = -0.84314565406494;
   fWeightMatrix0to1[2][2] = 1.13259215628381;
   fWeightMatrix0to1[3][2] = 6.63861100263575;
   fWeightMatrix0to1[4][2] = -0.310701504146308;
   fWeightMatrix0to1[5][2] = 3.62804882791345;
   fWeightMatrix0to1[6][2] = -0.0753885784161796;
   fWeightMatrix0to1[7][2] = -1.18611319860012;
   fWeightMatrix0to1[8][2] = 1.16060821547473;
   fWeightMatrix0to1[9][2] = 2.19741325089165;
   fWeightMatrix0to1[10][2] = -1.52471319833101;
   fWeightMatrix0to1[11][2] = 5.15272091469002;
   fWeightMatrix0to1[12][2] = 6.21464204413342;
   fWeightMatrix0to1[13][2] = -0.0667920227390396;
   fWeightMatrix0to1[0][3] = 3.37783211936191;
   fWeightMatrix0to1[1][3] = 3.24871725956192;
   fWeightMatrix0to1[2][3] = 2.06757828965483;
   fWeightMatrix0to1[3][3] = 0.356421212750316;
   fWeightMatrix0to1[4][3] = 0.356436772661406;
   fWeightMatrix0to1[5][3] = 0.196938239382442;
   fWeightMatrix0to1[6][3] = 1.1634193334306;
   fWeightMatrix0to1[7][3] = 1.22727776734047;
   fWeightMatrix0to1[8][3] = 1.19898620940481;
   fWeightMatrix0to1[9][3] = 1.93051944170752;
   fWeightMatrix0to1[10][3] = -1.27012600383789;
   fWeightMatrix0to1[11][3] = 0.741097349440049;
   fWeightMatrix0to1[12][3] = -0.499845772054704;
   fWeightMatrix0to1[13][3] = -0.890194575982621;
   fWeightMatrix0to1[0][4] = -2.4673332981788;
   fWeightMatrix0to1[1][4] = -2.3879162898737;
   fWeightMatrix0to1[2][4] = 0.809466304861997;
   fWeightMatrix0to1[3][4] = 0.522785147703907;
   fWeightMatrix0to1[4][4] = -1.31430522383953;
   fWeightMatrix0to1[5][4] = 3.2326436302132;
   fWeightMatrix0to1[6][4] = 0.292577903914076;
   fWeightMatrix0to1[7][4] = -0.0354404964101198;
   fWeightMatrix0to1[8][4] = 1.18535899564772;
   fWeightMatrix0to1[9][4] = -0.859597548946425;
   fWeightMatrix0to1[10][4] = -0.177251083755218;
   fWeightMatrix0to1[11][4] = -0.666458141336369;
   fWeightMatrix0to1[12][4] = 0.825891685781207;
   fWeightMatrix0to1[13][4] = -0.999395533952497;
   fWeightMatrix0to1[0][5] = -0.654956792134068;
   fWeightMatrix0to1[1][5] = -0.551882528918228;
   fWeightMatrix0to1[2][5] = 0.214327236680008;
   fWeightMatrix0to1[3][5] = 0.478992123824078;
   fWeightMatrix0to1[4][5] = 0.845855787616985;
   fWeightMatrix0to1[5][5] = 0.539275815538733;
   fWeightMatrix0to1[6][5] = -1.01342806315889;
   fWeightMatrix0to1[7][5] = -0.301010663526323;
   fWeightMatrix0to1[8][5] = 0.206513562651446;
   fWeightMatrix0to1[9][5] = -0.42466657712495;
   fWeightMatrix0to1[10][5] = 1.60981744233884;
   fWeightMatrix0to1[11][5] = -0.123292865786097;
   fWeightMatrix0to1[12][5] = 0.531770900747025;
   fWeightMatrix0to1[13][5] = -0.246747994218486;
   fWeightMatrix0to1[0][6] = -0.0469308058961721;
   fWeightMatrix0to1[1][6] = -0.0262990627117448;
   fWeightMatrix0to1[2][6] = 0.206332250447895;
   fWeightMatrix0to1[3][6] = 0.269017375258141;
   fWeightMatrix0to1[4][6] = -1.46073156316983;
   fWeightMatrix0to1[5][6] = 0.134248954976842;
   fWeightMatrix0to1[6][6] = 0.00308680513606604;
   fWeightMatrix0to1[7][6] = -0.035877839562501;
   fWeightMatrix0to1[8][6] = 0.294565905693919;
   fWeightMatrix0to1[9][6] = 0.107855819549022;
   fWeightMatrix0to1[10][6] = -0.59681186694639;
   fWeightMatrix0to1[11][6] = -0.0513362461203063;
   fWeightMatrix0to1[12][6] = 0.328300759698126;
   fWeightMatrix0to1[13][6] = -0.179398698573054;
   fWeightMatrix0to1[0][7] = -0.6689492502686;
   fWeightMatrix0to1[1][7] = -0.329136464951921;
   fWeightMatrix0to1[2][7] = -1.36953779368067;
   fWeightMatrix0to1[3][7] = -1.45619499190378;
   fWeightMatrix0to1[4][7] = 1.01535828671908;
   fWeightMatrix0to1[5][7] = 1.25769092738341;
   fWeightMatrix0to1[6][7] = -0.174056772469872;
   fWeightMatrix0to1[7][7] = 2.55392410345864;
   fWeightMatrix0to1[8][7] = -0.402660740540723;
   fWeightMatrix0to1[9][7] = -0.0319995152458401;
   fWeightMatrix0to1[10][7] = 0.377576466066043;
   fWeightMatrix0to1[11][7] = 2.53707693392414;
   fWeightMatrix0to1[12][7] = -1.01195858231229;
   fWeightMatrix0to1[13][7] = 2.34914771245282;
   fWeightMatrix0to1[0][8] = 1.16724889336767;
   fWeightMatrix0to1[1][8] = -3.57505381999787;
   fWeightMatrix0to1[2][8] = 0.03261350649285;
   fWeightMatrix0to1[3][8] = 0.443636405787391;
   fWeightMatrix0to1[4][8] = 0.967600326404691;
   fWeightMatrix0to1[5][8] = 0.496101841785961;
   fWeightMatrix0to1[6][8] = 1.78816858543631;
   fWeightMatrix0to1[7][8] = 0.685343075771011;
   fWeightMatrix0to1[8][8] = -2.99005031587489;
   fWeightMatrix0to1[9][8] = 0.577102696551989;
   fWeightMatrix0to1[10][8] = 0.0726009760523691;
   fWeightMatrix0to1[11][8] = 1.79782393747906;
   fWeightMatrix0to1[12][8] = 6.26829734906764;
   fWeightMatrix0to1[13][8] = -2.40877080902089;
   fWeightMatrix0to1[0][9] = 0.159817934586132;
   fWeightMatrix0to1[1][9] = 1.4636520750274;
   fWeightMatrix0to1[2][9] = -1.27732219373026;
   fWeightMatrix0to1[3][9] = 2.92481008359373;
   fWeightMatrix0to1[4][9] = -0.0137843843033842;
   fWeightMatrix0to1[5][9] = -2.97202972444498;
   fWeightMatrix0to1[6][9] = 1.65663794327281;
   fWeightMatrix0to1[7][9] = -1.34410693540689;
   fWeightMatrix0to1[8][9] = 1.32623843256181;
   fWeightMatrix0to1[9][9] = 2.26906769624727;
   fWeightMatrix0to1[10][9] = 2.18814334099389;
   fWeightMatrix0to1[11][9] = 2.32216958240503;
   fWeightMatrix0to1[12][9] = -2.31976051760154;
   fWeightMatrix0to1[13][9] = 6.30722350832291;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.394983127671411;
   fWeightMatrix1to2[0][1] = -0.514102084647603;
   fWeightMatrix1to2[0][2] = -0.795938726366417;
   fWeightMatrix1to2[0][3] = -0.545819562461206;
   fWeightMatrix1to2[0][4] = -0.783493896326949;
   fWeightMatrix1to2[0][5] = 0.124576451167225;
   fWeightMatrix1to2[0][6] = 0.70727729603895;
   fWeightMatrix1to2[0][7] = -0.353281406504418;
   fWeightMatrix1to2[0][8] = -0.535255345127342;
   fWeightMatrix1to2[0][9] = 0.188562947537964;
   fWeightMatrix1to2[0][10] = -0.293167841726564;
   fWeightMatrix1to2[0][11] = 0.564171719795525;
   fWeightMatrix1to2[0][12] = 0.62970516977089;
   fWeightMatrix1to2[0][13] = -1.11542704163169;
   fWeightMatrix1to2[0][14] = 0.0969641611721008;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 147.195877075;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 458.580871582;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 458.580871582;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 159.764877319;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 228.585403442;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 228.585403442;
   fMin_1[0][2] = 5.00555372238;
   fMax_1[0][2] = 182.340270996;
   fMin_1[1][2] = 5.00002384186;
   fMax_1[1][2] = 222.360198975;
   fMin_1[2][2] = 5.00002384186;
   fMax_1[2][2] = 222.360198975;
   fMin_1[0][3] = 0.950001418591;
   fMax_1[0][3] = 1;
   fMin_1[1][3] = 0.950001418591;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0.950001418591;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0.0292470622808;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0.0169777330011;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0.0169777330011;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 0.900638699532;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0.900001347065;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0.900001347065;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.500291585922;
   fMax_1[0][6] = 1.29818689823;
   fMin_1[1][6] = 0.500000476837;
   fMax_1[1][6] = 1.29995691776;
   fMin_1[2][6] = 0.500000476837;
   fMax_1[2][6] = 1.29995691776;
   fMin_1[0][7] = -2800.08886719;
   fMax_1[0][7] = 49.933013916;
   fMin_1[1][7] = -13428.9570312;
   fMax_1[1][7] = 49.9973716736;
   fMin_1[2][7] = -13428.9570312;
   fMax_1[2][7] = 49.9973716736;
   fMin_1[0][8] = -428.769165039;
   fMax_1[0][8] = 4.98479652405;
   fMin_1[1][8] = -6812.04101562;
   fMax_1[1][8] = 4.9993929863;
   fMin_1[2][8] = -6812.04101562;
   fMax_1[2][8] = 4.9993929863;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
