// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.0         [262400]
ROOT Release   : 5.28/00       [334848]
Creator        : tianjp
Date           : Sun Oct 20 14:56:32 2013
Host           : Linux cw103.cc.kek.jp 2.6.18-164.el5 #1 SMP Tue Aug 18 15:51:48 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gpfs/fs01/ilc/tianjp/analysis/PostDBD/zhh/llhh/lepOpt/macros_e2e2hh_bbbb
Training events: 68616
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "True" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10" [Number of updates for regulator before stop training]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
coneec                        coneec                        coneec                        coneec                                                          'c'    [0,208.902877808]
coneen                        coneen                        coneen                        coneen                                                          'c'    [0,200.94833374]
momentum                      momentum                      momentum                      momentum                                                        'm'    [5.03026533127,182.838287354]
coslarcon                     coslarcon                     coslarcon                     coslarcon                                                       'c'    [0.950001180172,1]
energyratio                   energyratio                   energyratio                   energyratio                                                     'e'    [0.0286631472409,1]
yokeenergy                    yokeenergy                    yokeenergy                    yokeenergy                                                      'y'    [1.20028758049,97.440071106]
nsigd0                        nsigd0                        nsigd0                        nsigd0                                                          'n'    [-11989.9111328,4.99600887299]
nsigz0                        nsigz0                        nsigz0                        nsigz0                                                          'n'    [-4558.32275391,4.99890851974]
totalcalenergy                totalcalenergy                totalcalenergy                totalcalenergy                                                  't'    [0,37.7682533264]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "coneec", "coneen", "momentum", "coslarcon", "energyratio", "yokeenergy", "nsigd0", "nsigz0", "totalcalenergy" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'c';
      fType[1] = 'c';
      fType[2] = 'm';
      fType[3] = 'c';
      fType[4] = 'e';
      fType[5] = 'y';
      fType[6] = 'n';
      fType[7] = 'n';
      fType[8] = 't';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[15][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0425047500986969;
   fWeightMatrix0to1[1][0] = 0.298743234474555;
   fWeightMatrix0to1[2][0] = 1.08146424725124;
   fWeightMatrix0to1[3][0] = 1.7283745282242;
   fWeightMatrix0to1[4][0] = -0.436462557429015;
   fWeightMatrix0to1[5][0] = 0.236207370792695;
   fWeightMatrix0to1[6][0] = -1.02122163746891;
   fWeightMatrix0to1[7][0] = 1.838414983384;
   fWeightMatrix0to1[8][0] = -1.17293754365793;
   fWeightMatrix0to1[9][0] = -1.1620199712348;
   fWeightMatrix0to1[10][0] = -1.9965935929441;
   fWeightMatrix0to1[11][0] = 1.14374321000274;
   fWeightMatrix0to1[12][0] = -1.12132156776614;
   fWeightMatrix0to1[13][0] = 2.88973857173092;
   fWeightMatrix0to1[0][1] = -0.27129918247404;
   fWeightMatrix0to1[1][1] = 0.0420673479354677;
   fWeightMatrix0to1[2][1] = -0.119316018241172;
   fWeightMatrix0to1[3][1] = 1.74026249491624;
   fWeightMatrix0to1[4][1] = -0.647838115327492;
   fWeightMatrix0to1[5][1] = 0.0766094666162713;
   fWeightMatrix0to1[6][1] = -0.925640583682256;
   fWeightMatrix0to1[7][1] = -1.13123363153882;
   fWeightMatrix0to1[8][1] = 0.996128268599502;
   fWeightMatrix0to1[9][1] = -0.659575964423291;
   fWeightMatrix0to1[10][1] = -1.47276080771098;
   fWeightMatrix0to1[11][1] = 0.689486710466346;
   fWeightMatrix0to1[12][1] = 1.62689404654365;
   fWeightMatrix0to1[13][1] = -0.631486609123169;
   fWeightMatrix0to1[0][2] = -1.00115992850909;
   fWeightMatrix0to1[1][2] = 0.898529873027017;
   fWeightMatrix0to1[2][2] = 1.19251405222648;
   fWeightMatrix0to1[3][2] = 1.6570370273986;
   fWeightMatrix0to1[4][2] = -1.67111052997073;
   fWeightMatrix0to1[5][2] = -2.20446191810438;
   fWeightMatrix0to1[6][2] = 0.0774517945626155;
   fWeightMatrix0to1[7][2] = -0.512500370784264;
   fWeightMatrix0to1[8][2] = -0.486425834665259;
   fWeightMatrix0to1[9][2] = 6.04943118904892;
   fWeightMatrix0to1[10][2] = -1.26684327382764;
   fWeightMatrix0to1[11][2] = 2.12276477107057;
   fWeightMatrix0to1[12][2] = 1.09506432681158;
   fWeightMatrix0to1[13][2] = 0.204668885561188;
   fWeightMatrix0to1[0][3] = 2.03554752652687;
   fWeightMatrix0to1[1][3] = 3.23517680121126;
   fWeightMatrix0to1[2][3] = -0.337014276588375;
   fWeightMatrix0to1[3][3] = -1.62859823370746;
   fWeightMatrix0to1[4][3] = 2.30818043625272;
   fWeightMatrix0to1[5][3] = -1.19148950604772;
   fWeightMatrix0to1[6][3] = 1.49621046740741;
   fWeightMatrix0to1[7][3] = 1.07755324157468;
   fWeightMatrix0to1[8][3] = 0.33443408085755;
   fWeightMatrix0to1[9][3] = 0.108907698643144;
   fWeightMatrix0to1[10][3] = -0.926193254844089;
   fWeightMatrix0to1[11][3] = 1.38353543917409;
   fWeightMatrix0to1[12][3] = -1.686761961838;
   fWeightMatrix0to1[13][3] = -0.341056794058071;
   fWeightMatrix0to1[0][4] = -3.69147144099486;
   fWeightMatrix0to1[1][4] = -3.08199145465673;
   fWeightMatrix0to1[2][4] = 1.2771815424413;
   fWeightMatrix0to1[3][4] = 0.683870467534883;
   fWeightMatrix0to1[4][4] = -2.92560058275208;
   fWeightMatrix0to1[5][4] = 0.0725535449785118;
   fWeightMatrix0to1[6][4] = -0.0962142202769441;
   fWeightMatrix0to1[7][4] = 0.508454010468889;
   fWeightMatrix0to1[8][4] = 2.00433621280114;
   fWeightMatrix0to1[9][4] = 0.288362171365088;
   fWeightMatrix0to1[10][4] = 0.0600026072801409;
   fWeightMatrix0to1[11][4] = -0.847256356806782;
   fWeightMatrix0to1[12][4] = 0.658790611826515;
   fWeightMatrix0to1[13][4] = -1.72322988457415;
   fWeightMatrix0to1[0][5] = 0.0876232125100557;
   fWeightMatrix0to1[1][5] = -1.28958575547725;
   fWeightMatrix0to1[2][5] = 1.03273549591124;
   fWeightMatrix0to1[3][5] = 1.13297217405974;
   fWeightMatrix0to1[4][5] = 0.454323521216261;
   fWeightMatrix0to1[5][5] = 0.0498148358162243;
   fWeightMatrix0to1[6][5] = -2.12665896886551;
   fWeightMatrix0to1[7][5] = -1.06776476283211;
   fWeightMatrix0to1[8][5] = 0.917396138926485;
   fWeightMatrix0to1[9][5] = -0.394652234407651;
   fWeightMatrix0to1[10][5] = 1.25958196243649;
   fWeightMatrix0to1[11][5] = -0.210569630679403;
   fWeightMatrix0to1[12][5] = 1.08169813342523;
   fWeightMatrix0to1[13][5] = -0.638184274599151;
   fWeightMatrix0to1[0][6] = -0.569810832887846;
   fWeightMatrix0to1[1][6] = -1.2955424843722;
   fWeightMatrix0to1[2][6] = 0.938187834548378;
   fWeightMatrix0to1[3][6] = -1.10911045707304;
   fWeightMatrix0to1[4][6] = -2.49735881981052;
   fWeightMatrix0to1[5][6] = -0.262324298143846;
   fWeightMatrix0to1[6][6] = 0.405569722077572;
   fWeightMatrix0to1[7][6] = -0.485179391936071;
   fWeightMatrix0to1[8][6] = 0.668001184097444;
   fWeightMatrix0to1[9][6] = 0.589868284943053;
   fWeightMatrix0to1[10][6] = -0.120508999360272;
   fWeightMatrix0to1[11][6] = 3.2479057882757;
   fWeightMatrix0to1[12][6] = -1.01089588237228;
   fWeightMatrix0to1[13][6] = -0.805642030659044;
   fWeightMatrix0to1[0][7] = -0.51790633128723;
   fWeightMatrix0to1[1][7] = -2.60654730636731;
   fWeightMatrix0to1[2][7] = -2.1259198218958;
   fWeightMatrix0to1[3][7] = -1.66295937729709;
   fWeightMatrix0to1[4][7] = -2.8006130530615;
   fWeightMatrix0to1[5][7] = 0.27073096168865;
   fWeightMatrix0to1[6][7] = -0.527855160376812;
   fWeightMatrix0to1[7][7] = 1.21659424774114;
   fWeightMatrix0to1[8][7] = -1.10214817038157;
   fWeightMatrix0to1[9][7] = 0.919290009007223;
   fWeightMatrix0to1[10][7] = 0.683654865802941;
   fWeightMatrix0to1[11][7] = 1.50233524893394;
   fWeightMatrix0to1[12][7] = -1.96541758844606;
   fWeightMatrix0to1[13][7] = -0.560369962706551;
   fWeightMatrix0to1[0][8] = -0.252825827421675;
   fWeightMatrix0to1[1][8] = -0.108485432022237;
   fWeightMatrix0to1[2][8] = -1.12353741096274;
   fWeightMatrix0to1[3][8] = 1.82708309566752;
   fWeightMatrix0to1[4][8] = -0.513999721061798;
   fWeightMatrix0to1[5][8] = -0.597298367511861;
   fWeightMatrix0to1[6][8] = 0.304825701963131;
   fWeightMatrix0to1[7][8] = -0.51302347806817;
   fWeightMatrix0to1[8][8] = -0.150697790120714;
   fWeightMatrix0to1[9][8] = 0.925608932694631;
   fWeightMatrix0to1[10][8] = -0.898220133758768;
   fWeightMatrix0to1[11][8] = 0.587647554628781;
   fWeightMatrix0to1[12][8] = 0.674083645694275;
   fWeightMatrix0to1[13][8] = 0.0832637919712508;
   fWeightMatrix0to1[0][9] = -1.2341830370868;
   fWeightMatrix0to1[1][9] = 0.790769303906318;
   fWeightMatrix0to1[2][9] = -2.07095309659686;
   fWeightMatrix0to1[3][9] = 1.06387060622678;
   fWeightMatrix0to1[4][9] = 1.96063665794292;
   fWeightMatrix0to1[5][9] = -0.432719430165132;
   fWeightMatrix0to1[6][9] = 1.276582368081;
   fWeightMatrix0to1[7][9] = -1.68656378035984;
   fWeightMatrix0to1[8][9] = -0.140037360107448;
   fWeightMatrix0to1[9][9] = 2.58899946452469;
   fWeightMatrix0to1[10][9] = 2.47646652557028;
   fWeightMatrix0to1[11][9] = -1.74261383090617;
   fWeightMatrix0to1[12][9] = 0.234698346360219;
   fWeightMatrix0to1[13][9] = 4.00306199191121;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.589532229835726;
   fWeightMatrix1to2[0][1] = -0.315300867051648;
   fWeightMatrix1to2[0][2] = -1.43512699144722;
   fWeightMatrix1to2[0][3] = -0.296763943289022;
   fWeightMatrix1to2[0][4] = -0.799434230815799;
   fWeightMatrix1to2[0][5] = 0.474970126701553;
   fWeightMatrix1to2[0][6] = 0.902478699674833;
   fWeightMatrix1to2[0][7] = -0.0565292303899349;
   fWeightMatrix1to2[0][8] = -0.717280853681729;
   fWeightMatrix1to2[0][9] = 0.221331671405526;
   fWeightMatrix1to2[0][10] = -0.306356510624978;
   fWeightMatrix1to2[0][11] = 0.427292982603031;
   fWeightMatrix1to2[0][12] = 1.57904432485315;
   fWeightMatrix1to2[0][13] = -0.897050104744075;
   fWeightMatrix1to2[0][14] = -0.523423180073662;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 138.821517944;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 208.902877808;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 208.902877808;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 130.466598511;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 200.94833374;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 200.94833374;
   fMin_1[0][2] = 7.30998516083;
   fMax_1[0][2] = 181.397979736;
   fMin_1[1][2] = 5.03026533127;
   fMax_1[1][2] = 182.838287354;
   fMin_1[2][2] = 5.03026533127;
   fMax_1[2][2] = 182.838287354;
   fMin_1[0][3] = 0.950001180172;
   fMax_1[0][3] = 1;
   fMin_1[1][3] = 0.950001180172;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0.950001180172;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0.0627488791943;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0.0286631472409;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0.0286631472409;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.20028758049;
   fMax_1[0][5] = 52.5313682556;
   fMin_1[1][5] = 1.20028758049;
   fMax_1[1][5] = 97.440071106;
   fMin_1[2][5] = 1.20028758049;
   fMax_1[2][5] = 97.440071106;
   fMin_1[0][6] = -58.3623847961;
   fMax_1[0][6] = 4.85773324966;
   fMin_1[1][6] = -11989.9111328;
   fMax_1[1][6] = 4.99600887299;
   fMin_1[2][6] = -11989.9111328;
   fMax_1[2][6] = 4.99600887299;
   fMin_1[0][7] = -56.1477165222;
   fMax_1[0][7] = 4.95874357224;
   fMin_1[1][7] = -4558.32275391;
   fMax_1[1][7] = 4.99890851974;
   fMin_1[2][7] = -4558.32275391;
   fMax_1[2][7] = 4.99890851974;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 37.7682533264;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 37.7682533264;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 37.7682533264;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
