from matplotlib.ticker import MultipleLocator

figure_options:dict[str, dict[str, dict]] = {
    'eebbbb': {
        'nisoelectrons': { 'xlabel': 'ISOElectrons',
            'plot_hist_kwargs': { 'int_bins': True },
            'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1), 'ild_text_position': 'upper right' } },
        'pairedLepType': { 'xlabel': 'pairedLepType',
            'plot_hist_kwargs': { 'int_bins': True },
            'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1), 'legend_kwargs': { 'loc': 'center' } } },
        'mzll': { 'xlabel': 'm_{ll}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'zhh_mh1': { 'xlabel': 'm_{H1}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'zhh_mh2': { 'xlabel': 'm_{H2}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'ptmiss': { 'xlabel': 'p_{t}^{miss}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'thrust': { 'xlabel': 'thrust', 'xlim': [0, 1] },
        'sumBTags': { 'xlabel': 'sum b-tags', 'xlim': [0, 4] },
        'bdtg1': { 'xlabel': 'bdtg1', 'xlim': [0, 1] },
        'bdtg2': { 'xlabel': 'bdtg2', 'xlim': [0, 1] },
        'bdtg3': { 'xlabel': 'bdtg3', 'xlim': [0, 1] },
        'bdtg4': { 'xlabel': 'bdtg4', 'xlim': [0, 1] },
        'bdtg5': { 'xlabel': 'bdtg5', 'xlim': [0, 1] }
    },
    'μμbbbb': {
        'nisomuons': { 'xlabel': 'ISOMuons',
            'plot_hist_kwargs': { 'int_bins': True },
            'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1), 'ild_text_position': 'upper right' } },
        'pairedLepType': { 'xlabel': 'pairedLepType',
            'plot_hist_kwargs': { 'int_bins': True },
            'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1), 'legend_kwargs': { 'loc': 'center' } } },
        'mzll': { 'xlabel': 'm_{ll}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'zhh_mh1': { 'xlabel': 'm_{H1}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'zhh_mh2': { 'xlabel': 'm_{H2}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'ptmiss': { 'xlabel': 'p_{t}^{miss}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'thrust': { 'xlabel': 'thrust', 'xlim': [0, 1] },
        'sumBTags': { 'xlabel': 'sum b-tags', 'xlim': [0, 4] },
        'bdtg1': { 'xlabel': 'bdtg1', 'xlim': [0, 1] },
        'bdtg2': { 'xlabel': 'bdtg2', 'xlim': [0, 1] },
        'bdtg3': { 'xlabel': 'bdtg3', 'xlim': [0, 1] },
        'bdtg4': { 'xlabel': 'bdtg4', 'xlim': [0, 1] },
        'bdtg5': { 'xlabel': 'bdtg5', 'xlim': [0, 1] },
    },
    'μμbbbb_4C': {
        'nisomuons': { 'xlabel': 'ISOMuons',
            'plot_hist_kwargs': { 'int_bins': True },
            'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1), 'ild_text_position': 'upper right' } },
        'pairedLepType': { 'xlabel': 'pairedLepType',
            'plot_hist_kwargs': { 'int_bins': True },
            'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1), 'legend_kwargs': { 'loc': 'center' } } },
        'fit4C_mz': { 'xlabel': 'm_{ll}^{4C}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'fit4C_mh1': { 'xlabel': 'm_{H1}^{4C}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'fit4C_mh2': { 'xlabel': 'm_{H2}^{4C}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'ptmiss': { 'xlabel': 'p_{t}^{miss}', 'xlim': [0, 300], 'xunit': 'GeV' },
        'thrust': { 'xlabel': 'thrust', 'xlim': [0, 1] },
        'sumBTags': { 'xlabel': 'sum b-tags', 'xlim': [0, 4] },
        'bdtg1': { 'xlabel': 'bdtg1', 'xlim': [0, 1] },
        'bdtg2': { 'xlabel': 'bdtg2', 'xlim': [0, 1] },
        'bdtg3': { 'xlabel': 'bdtg3', 'xlim': [0, 1] },
        'bdtg4': { 'xlabel': 'bdtg4', 'xlim': [0, 1] },
        'bdtg5': { 'xlabel': 'bdtg5', 'xlim': [0, 1] },        
    },
    'default': {
        'fit4C_mh1': { 'xlim': [0, 270], 'xunit': 'GeV' },
        'fit4C_mh2': { 'xlim': [0, 500], 'xunit': 'GeV' },
        'fit4C_mz': { 'xlim': [0, 550], 'xunit': 'GeV' }
    }
    #'vvbbbb': [
    #    { 'xlabel': 'IsoLeptons', 'plot_hist_kwargs': { 'int_bins': True }, 'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1) } },
    #    { 'xlabel': 'm_{H1}', 'xlim': [0, 250], 'xunit': 'GeV' },
    #    { 'xlabel': 'm_{H2}', 'xlim': [0, 250], 'xunit': 'GeV' },
    #    { 'xlabel': 'p_{t}^{miss}', 'xlim': [0, 200], 'xunit': 'GeV' },
    #    { 'xlabel': 'thrust' },
    #    { 'xlabel': 'E_{vis}' },
    #    { 'xlabel': 'm_{HH}', 'xunit': 'GeV' },
    #    { 'xlabel': 'bmax3' }
    #],
    #'qqbbbb': [
    #    { 'xlabel': 'IsoLeptons', 'plot_hist_kwargs': { 'int_bins': True }, 'ild_style_kwargs': { 'xminor': False, 'xlocator': MultipleLocator(1) } },
    #    { 'xlabel': 'm_{H1}', 'xlim': [0, 250], 'xunit': 'GeV' },
    #    { 'xlabel': 'm_{H2}', 'xlim': [0, 250], 'xunit': 'GeV' },
    #    { 'xlabel': 'p_{t}^{miss}', 'xlim': [0, 200], 'xunit': 'GeV' },
    #    { 'xlabel': 'thrust' },
    #    { 'xlabel': 'bmax4' }
    #]
}

for int_property in ['n_fermion',
    'n_higgs',
    'n_b_from_higgs',
    'n_c_from_higgs',
    'njets',
    'nisoleptons',
    'nisoelectrons',
    'nisomuons',
    'nisotaus',
    'npfos',
    'npfosmin4j',
    'npfosmax4j',
    'nJets',
    'nLeptons',
    'nSLDecayBHadron',
    'nSLDecayCHadron',
    'nSLDecayTauLepton',
    'nSLDecayTotal',
    'nCorrectedSLD']:
    
    figure_options['default'][int_property] = { 'xlabel': f'n_{int_property[1:]}', 'plot_hist_kwargs': { 'int_bins': True } }